# LOAD FETCHED DATA

# FIND GAPS BETWEEN HIGH AND LOW OF 1 AND 3 CANDLE, POKUD JE > 0 VRÁTÍ TRUE

# OMEZIT ČAS NA LOOP NA 10 AM EST - 11 AM EST

# POKUD CENA PO VYTVOŘENÍ TÉTO MEZERY DOSÁHNE HIGH CENY OR LOW CENY TÉTO MEZERY = TRUE
    
        #POKUD JE LOW PRICE VĚTŠÍ JAK HIGH PRICE = BUY

        # JINAK SELL 

# POKUD BUY = ČEKÁME AŽ CLOSE DALŠÍ SVÍČKY BUDE VĚTŠÍ NEŽ HIGH PŘEDCHOZÍ SVÍČKY
# POKUD SELL = ČEKÁME AŽ CLOSE DALŠÍ SVÍČKY BUDE MENŠÍ NEŽ LOW PŘEDCHOZÍ SVÍČKY

# OTEVŘENÍ POZICE - POKUD BUY - OTEVŘENÍ NA HIGH PŘEDCHOZÍ SVÍČKY PO UZAVŘENÍ DALŠÍ SVÍČKY
                    # POKUD SELL - OTEVŘENÍ NA LOW PŘEDCHOZÍ SVÍČKY PO UZAVŘENÍ DALŠÍ SVÍČKY
        
        # STOP LOSS - POKUD BUY - STOP LOSS O 1 PIP POD LOW PŘEDCHOZÍ NEBO DALŠÍ SVÍČKY (ZKONTROLOVAT OBOJÍ)  
                    # POKUD SELL - STOP LOSS O 1 PIP NAD HIGH PŘEDCHOZÍ NEBO DALŠÍ SVÍČKY (ZKONTROLOVAT OBOJÍ)

        # TAKE PROFIT 